name: Build aria2

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: windows-11-arm
            ARTIFACT_PREFIX: winarm64
            MSYS2_SYS: CLANGARM64
          - os: windows-latest
            ARTIFACT_PREFIX: win64
            MSYS2_SYS: MINGW64
    steps:
      - name: 'Configure git: core.autocrlf, core.eol'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.MSYS2_SYS}}
          update: true
          pacboy: >-
            autotools:p
            c-ares:p
            clang:a
            cppunit:p
            gcc:x
            gmp:p
            gnutls:p
            libgcrypt:p
            libgpg-error:p
            libssh2:p
            libtool:p
            libxml2:p
            nettle:p
            pkgconf:p
            sqlite3:p
            zlib:p
      - name: Build
        shell: msys2 {0}
        run: |
          autoreconf -i
          ARIA2_STATIC=yes ./configure
          make -j4
      - name: Copy files
        shell: msys2 {0}
        run: |
          mkdir upload
          cp src/aria2c.exe upload
          strip upload/aria2c.exe
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aria2-git-${{matrix.ARTIFACT_PREFIX}}-${{github.sha}}
          path: upload
          if-no-files-found: error
